<a href="https://colab.research.google.com/github/PatMis16/linAlgGoogleColab/blob/main/linAlg_Codierungstheorie_Patrick_Mischler.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Codierungstheorie





## Einleitung in die Codierungstheorie

In einem alten Kinderspiel startet ein Kind damit, dass es einem anderen Kind eine Nachricht (ein Wort oder ein kurzer Satz) zuflüstert. Diese Nachricht wird dann von Kind zu Kind weitergegeben. Das letzte Kind in der Reihe gibt die zugeflüsterte Nachricht laut wieder. Oft mit dem Ergebnis das nicht genau das wiedergegeben wird, was das erste Kind weitergegeben hat. Es finden also bei der Übertragung Fehler statt. Übertragungsfehler können sich durch verschiedene Arten von Störungen auch beim elektronischen übertragen von Daten ergeben. So können beispielsweise elektromagnetische Störungen dazu führen das bei der Übertragung ein Bit-Fehler auftritt. Dabei wird eine 1 zu einer 0 oder Umgekehrt. 
Hinter der Codierungstheorie steht die Idee, dass Fehler bei der Übermittlung von Daten erkannt und sogar korrigiert werden können. Eine einfache jedoch nicht gerade effiziente Methode wäre es, eine Nachricht mehrmals zu übertragen und dann jeweils gegeneinander zu prüfen. Somit wäre sichergestellt, dass Fehler zumindest erkannt werden könnten. Allerdings ist die Fehlererkennung eingeschränkt. Betrachten wir ein Beispiel, bei dem die Nachricht 3-mal übertragen wird.

1. > Lorem ipsum dolor
2. > Lorem *a*psum dolor
3. > Lorem ipsum dolor

Wir sehen das bei der 2. Übertragung ein Fehler beim zweiten Wort aufgetreten ist. Dies lässt sich daran erkennen, dass sie Nachricht bei der 1. und 3. Übertragung korrekt ist. Würde aber folgendes Übertragen:

1. > Lorem *a*psum dolor
2. > Lorem *a*psum dolor
3. > Lorem ipsum dolor

Würde *ipsum* fälschlicherwe als Fehler identifiziert, da die beiden *apsum* in der Überzahl sind. 
Zudem wird hier die 3-fache Datenmenge übertragen, was dieses Verfahren nicht sehr effizient macht. 

Der amerikanische Mathematiker *Richard W. Hamming* hat für diesen Zweck eine einfache und doch effiziente Methode entwickelt welche *Hamming-Code* genannt wird. Der Einsatz reicht von der Fehlerprüfung bei der Datenübertragung im Netzwerk bis zu der Fehlererkennung in ECC-Speicherchips.

## Theorieteil
Der *Hamming-Code* gehört zu den linearen Codes und bezieht sich auf Binärziffern. Das bedeutet, wir bewegen uns um Körper $\mathbb{Z}_2$ [[Weitz. 2018.]](zotero://select/items/_C9DWSI2S) . Dabei bezieht sich der Begriff *Hamming-Code* auf einen Code mit einer Prüfmatrix $(E|B)$ mit der Form $(m \times (2^m -1))$ [[Socher. 2022.]](zotero://select/items/_QGF4J2P6). 
Der *Hamming-Code* kann in verschiedenen Längen implementiert werden. *Hamming-Codes* weisen einen *Hamming-Abstand* von 3 auf. Dies bedeutet, dass sich die Codewörter um mindestens 3 Bit unterschieden müssen. Damit lassen sich bis zu zwei Bitfehler in einem Code erkennen, aber nur ein Bitfehler kann korrigiert werden. Beim erweiterten *Hamming-Code* mit einem *Hamming-Abstand* von 4, können mit hilfe eines zusätzlichen Paritätsbit bis zu drei Bitfehler erkennen, jedoch kann auch nur ein Fehler korrigiert werden [Hamming Code 2020.](zotero://select/items/_8C9CJA2Z). Ein *Hamming-Code* ist somit durch seine Länge $N$, die Anzahl Paritätsbits $k$, den *Hamming-Abstand* $d$ und die Anzahl Datenbits $n$ bestimmt. Dies ergiebt einen sogenannten $N$-$k$-$d$-Code, wobei man bei der Bezeichnung eines *Hamming-Codes* meistens nur die Gesamtlänge $N$ und die Anzahl Datenbits $n$, Gesamtlänge abzüglich der Prüfbits, als Bezeichnung verwendet werden.

$$
\begin{aligned}
N &= 2^k - 1 = \text{Gesamtlänge} \\
k &= ~ \text{Paritätsbits} \\
d &= ~\text{Hamming-Abstand} \\
n &= 2^k-k-1 = \text{Datenbits} \\
\end{aligned}
$$

Besteht ein Datenpaket nun aus 7 Zeichen, müssen 3 davon für das Prüfen und korrigieren verwendet werden, damit der Code funktioniert. Als $N$-$k$-$d$-Code wird dies als $[7,4,3]$-Code bezeichnet. Für den *Hamming-Code* schreibt man $(7,4)$-*Hamming-Code*. Das Verhältnis von Nutzlast zu der Menge der übertragenen Daten ist bei diesem Beispiel eher schlecht. Allerdings verbessert sich das Verhältnis mit zunehmender Anzahl Zeichen (Bits), welche in einem Paket übermittelt werden.

Prinzip: Wird ein Vektor bestehend aus 0 und 1 mit einem Vektor bestehend aus "nur" 1 multipliziert, erhält man Anzahl 1 in v.

$$
\vec{v_1} = \begin{pmatrix} 0 \\ 1 \\ 1 \\ 1 \end{pmatrix},
\vec{v_2} = \begin{pmatrix} 1 \\ 0 \\ 0 \\ 1 \end{pmatrix},
\vec{v_3} = \begin{pmatrix} 0 \\ 0 \\ 0 \\ 0 \end{pmatrix}, 
\vec{a} = \begin{pmatrix} 1 \\ 1 \\ 1 \\ 1 \end{pmatrix} \\
~\\
\begin{aligned}
\vec{v_1}\vec{a}&=3 \\
\vec{v_2}\vec{a}&=2 \\
\vec{v_3}\vec{a}&=0
\end{aligned}
$$

In Python kann diese Berechnung ebenfalls durchgeführt werden. Dazu wird die Bibliothek `numpy` mit den entsprechenden Funktionen für die Matrixmultiplikation verwendet. 

In [43]:
import numpy as np

v1 = np.array([0,1,1,1])
v2 = np.array([1,0,0,1])
v3 = np.array([0,0,0,0])

a = np.array([1,1,1,1])
print(v1)
print(np.matmul(v1, a))
print(np.matmul(v2, a))
print(np.matmul(v3, a))

[0 1 1 1]
3
2
0


Die Vektoren können nun als **Codewort** bezeichtnet werden. Werden die Codewörter nun um ein Kontrollbit ergänzt [[Teschl. 2013]](zotero://select/items/_85KJXNKN), kann eine **Generatormatrix** erstellt werden. Die Generatormatrix besteht aus einer Einheitsmatrix. Die Einheitsmatix wird für die zu übertragende Nutzlast gebildet. Beispielsweise für 4 Bit:

$$
I_4 = 
\begin{pmatrix}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1
\end{pmatrix}
$$

Die Einheitsmatrix $I$ wird nun mit den Vektoren ergänzt, die bei der Multiplikation mit dem zu codierenden Wort bei einer geraden Anzahl Einsen eine $0$ und bei ungerader Anzahl Einsen eine $0$ ergiebt. Das Egebnis ist eine Generatormatrix $G_4$:

$$
G_4 = 
\begin{pmatrix}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1 \\
\color{green}1 & \color{green}0 & \color{green}1 & \color{green}1 \\
\color{red}1 & \color{red}1 & \color{red}0 & \color{red}1 \\
\color{pink}0 & \color{pink}1 & \color{pink}1 & \color{pink}1
\end{pmatrix}
$$

Wid nun die Generatormatrix beispielsweise mit dem *Null-Wort* $a = (0, 0, 0, 0)^T$ multipliziert, ist die Anzahl Einsen ungerade und somit die sogenannten **Paritätsbits** gleich $0$.

$$
C = G \cdot a = 
\begin{pmatrix}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1 \\
\color{green}1 & \color{green}0 & \color{green}1 & \color{green}1 \\
\color{red}1 & \color{red}1 & \color{red}0 & \color{red}1 \\
\color{pink}0 & \color{pink}1 & \color{pink}1 & \color{pink}1
\end{pmatrix} 
\cdot
\begin{bmatrix}
0 \\
0 \\
0 \\
0
\end{bmatrix}
= (0,0,0,0,0,0,0)^T
$$

Dies lässt sich auch mit Python einfach nachvollziehen:

In [44]:
import numpy as np

G = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1], [1, 0, 1, 1], [1, 1, 0, 1], [0, 1, 1, 1]])
a = np.array([0, 0, 0, 0])
result = np.matmul(G, a)
result[result % 2 == 0] = 0
print(result)

[0 0 0 0 0 0 0]


Für ein gültiges Codewort beispielsweis $b=(0,0,0,1)^T$  ergibt sich eine gerade Anzahl von Einsen. 

$$
C = G \cdot b = 
\begin{pmatrix}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1 \\
\color{green}1 & \color{green}0 & \color{green}1 & \color{green}1 \\
\color{red}1 & \color{red}1 & \color{red}0 & \color{red}1 \\
\color{pink}0 & \color{pink}1 & \color{pink}1 & \color{pink}1
\end{pmatrix} 
\cdot
\begin{bmatrix}
0 \\
0 \\
0 \\
1
\end{bmatrix}
= (0,0,0,1,1,1,1)^T
$$

Auch dies lässt sich mit Hilfe von Python einfach berechnen:

In [45]:
import numpy as np

G = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1], [1, 0, 1, 1], [1, 1, 0, 1], [0, 1, 1, 1]])
b = np.array([0, 0, 0, 1])
result = np.where(np.matmul(G, b) % 2 == 0, 0, 1)
print(result)

[0 0 0 1 1 1 1]


Wird die Generatormatrix $G$ mit einem ungültigen Codewort $c = (0,0,1,1)$ multipliziert, ergeben sich eine ungerade Anzahl von Einsen:

$$
C = G \cdot c = 
\begin{pmatrix}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1 \\
\color{green}1 & \color{green}0 & \color{green}1 & \color{green}1 \\
\color{red}1 & \color{red}1 & \color{red}0 & \color{red}1 \\
\color{pink}0 & \color{pink}1 & \color{pink}1 & \color{pink}1
\end{pmatrix} 
\cdot
\begin{bmatrix}
0 \\
0 \\
1 \\
1
\end{bmatrix}
= (0,0,1,1,0,1,0)^T
$$

Auch dieses Beispiel lässt sich mit Python nachvollziehen:

In [46]:
import numpy as np

G = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1], [1, 0, 1, 1], [1, 1, 0, 1], [0, 1, 1, 1]])
c = np.array([0, 0, 1, 1])
result = np.matmul(G, c)
result[result % 2 == 0] = 0
print(result)

c2 = np.array([1, 0, 1, 1])
result = np.where(np.matmul(G, c2) % 2 == 0, 0, 1)
print(result)

[0 0 1 1 0 1 0]
[1 0 1 1 1 0 0]


Tritt nun bei der Übertragung eines Codewortes ein Fehler auf, kann dies mithilfe einer Prüfmatrix $H$ (Check-Matrix) erkannt und korrigiert werden. Dazu wird eine Einheitsmatrix $I_k$ mit den Paritätsbits ergänzt. $k$ bezieht sich auf die Anzahl der Paritätsbits. Bei einer Nutzlast von 4 Bit ergeben sich 3 Paritätsbits, daher $I_3$. 

$$
I_3=
\begin{pmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{pmatrix}
$$

Die Paritätsbits können aus der Generatormatrix übernommen werden. Die Prüfmatrix $H_4$ hat dementsprechend folgende Form:

$$
H_4=
\begin{pmatrix}
1 & 0 & 1 & 1 & 1 & 0 & 0 \\
1 & 1 & 0 & 1 & 0 & 1 & 0 \\
0 & 1 & 1 & 1 & 0 & 0 & 1
\end{pmatrix}
$$

Die Prüfmatrix $H_4$ kann nun zur Überprüfung von übertragenen Codewörtern verwendet werden. Damit lässt sich nun feststellen, ob bei der Übertragung Fehler aufgetreten sind. Dazu wird die Prüfmatrix $H_4$ mit dem Codewort $C$ multipliziert, was zum Ergebnis Vektor $\overrightarrow{z}$ führt.

Beispiel ohne Bit-Fehler:

$$
\overrightarrow{z} = H_4 \cdot C = 
\begin{pmatrix}
1 & 0 & 1 & 1 & 1 & 0 & 0 \\
1 & 1 & 0 & 1 & 0 & 1 & 0 \\
0 & 1 & 1 & 1 & 0 & 0 & 1
\end{pmatrix}
\cdot
\begin{pmatrix}
0 \\
1 \\
0 \\
1 \\
0 \\
1 \\
1 \\
\end{pmatrix}
=
\begin{bmatrix}
0 \\
0 \\
0
\end{bmatrix}
$$

Auch das lässt sich wieder mit Python nacvollziehen.

In [47]:
import numpy as np

H4 = np.array([[1, 0, 1, 1, 1, 0, 0], [1, 1, 0, 1, 0, 1, 0], [0, 1, 1, 1, 0, 0, 1]])
C = np.array([0, 1, 0, 1, 0, 1, 1])
result = np.where(np.matmul(H4, C) % 2 == 0, 1, 0)
print(result)

[0 0 0]


Beispiel mit Bit-Fehler im Codewort $C_f$

$$
\overrightarrow{z} = H_4 \cdot C_f = 
\begin{pmatrix}
1 & 0 & 1 & 1 & 1 & 0 & 0 \\
1 & 1 & 0 & 1 & 0 & 1 & 0 \\
0 & 1 & 1 & 1 & 0 & 0 & 1
\end{pmatrix}
\cdot
\begin{pmatrix}
0 \\
\color{red}1 \\
1 \\
0 \\
0 \\
1 \\
1 \\
\end{pmatrix}
=
\begin{bmatrix}
1 \\
1 \\
0
\end{bmatrix}
$$

Und wieder die entsprechende Berechnung in Python.

In [48]:
import numpy as np

H4 = np.array([[1, 0, 1, 1, 1, 0, 0], [1, 1, 0, 1, 0, 1, 0], [0, 1, 1, 1, 0, 0, 1]])
Cf = np.array([0, 0, 1, 1, 0, 1, 1])
result = np.where(np.matmul(H4, Cf) % 2 == 0, 0, 1)
print(result)

Cf2 = np.array([1, 0, 1, 1, 1, 0, 0])
result = np.where(np.matmul(H4, Cf2) % 2 == 0, 0, 1)
print(result)

[0 0 1]
[0 0 0]


Aus dem resultierenden Vektor $\overrightarrow{z}$ ist nun nicht nur ersichtlich das ein Fehler aufgetreten ist, sondern auch an welcher Stelle dieser sich befindet. Der Binäre Wert des Vektors $overrightarrow{z}$ kann ausgewiertet werden: $0\cdot 2^0 + 1\cdot 2^1 + 1 \cdot 2^2$ 

## Praktischer Teil

Im ersten Teil wird eine Klass erstellt, mit dem sich für einen Hammincode, alle Notwendigen funktionen wie das Generieren einer Generator-Matrix und einer Prüfmatrix erstellen lässt.

Der zweite Teil stellt das Hauptprogramm dar, in dem die Berechnungen durchgeführt werden.


### Klasse HammingCode

Die Klasse `HammingCode` besteht zum einen aus einem Konstruktor `__init__` in dem eine Instanz der Klasse (Objekt) mit den gegeben Angaben erzeugt wird. Der Konstruktor akzeptiert einen Parameter `k` mit dem die Anzahl Paritätsbits für das instanzierte `HemmingCode`-Objekt initialisiert wird. Bei der Initialisierung werden automatisch die Generatormatrix mit der Funktion `__construct_gen_matrix`, die Prüfmatrix mit der Funktion `__construct_chk_matrix` und die Decodierungs-Matrix mit der Funktion `__construct_encode_matrix()` erzeugt.

In [49]:
class HammingCode:
    """
    Klasse zur verarbeitung von Hamming-Codes
    """
    def __init__(self, k):
        """
        Initialisierung einer HammingCode-Instanz
        :param k: Anzahl der Paritätsbits im HammingCode
        """
        self.k = k  # number of parity bits
        self.N = 2**k - 1  # code length
        self.p = 2 ** k - k - 1  # payload bits
        self.__construct_chk_matrix()  # construct the check matrix
        self.__construct_gen_matrix()  # construct the generator matrix
        self.__construct_encode_matrix()  # construct the encode matrix

    def __construct_gen_matrix(self):
        """
        Konstruktion der Generator-Matrix für die HammingCode-Instanz
        :return: none
        """
        id_matrix = np.identity(self.p)
        self.gen_matrix = np.append(id_matrix, self.parity_matrix, axis=0)

    def __construct_chk_matrix(self):
        """
        Konstruktion der Prüfmatrix für die HammingCode-Instanz
        :return: none
        """
        id_matrix = np.identity(self.k)
        self.chk_matrix = ""
        tmp_check_matrix = ""
        for i in range(1, self.N+1):
            bin_num_rep = bin(i)[2:]
            bin_num_arr = self.__to_array(bin_num_rep)
            while len(bin_num_arr) < self.k:
                bin_num_arr.insert(0, 0)
            if i == 1:
                tmp_check_matrix = np.array([bin_num_arr[::-1]])
            else:
                tmp_check_matrix = np.vstack((tmp_check_matrix, bin_num_arr[::-1]))
        nonsy_chk_matrix = tmp_check_matrix.T
        one_pos = []
        for i in range(self.N):
            if np.sum(nonsy_chk_matrix[:, i]) == 1:
                one_pos.append(i)
        self.parity_matrix = np.delete(nonsy_chk_matrix, one_pos, 1)
        self.chk_matrix = np.hstack((self.parity_matrix, id_matrix))

    def __construct_encode_matrix(self):
        """
        Konstruktion der Decodierungs-Matrix fir die HammingCode-Instanz
        :return: none
        """
        id_matrix = np.identity(self.p)
        null_matrix = np.zeros((self.p, self.k))
        self.encode_matrix = np.hstack((null_matrix, id_matrix))

    @staticmethod
    def __to_array(input_string):
        """
        Methode zur Rückgabe eines Integers aus für jedes Zeichen eines Strings
        :param input_string: Eingabe-String
        :return: Integer
        """
        return [int(x) for x in str(input_string)]

    def get_length(self):
        """
        Methode zur Rückgabe der Code-Länge
        :return: Code-Länge als Integer
        """
        return self.N

    def get_payload(self):
        return self.p

    def get_generator_matrix(self):
        """
        Methode um die Generator-Matrix auszugeben.
        :return: generator matrix
        """
        return self.gen_matrix

    def get_check_matrix(self):
        """
        Methode um die Prüfmatrix auszugeben.
        :return: check matrix
        """
        return self.chk_matrix
    
    def get_encoding_matrix(self):
        """
        Metode zur rückgabe der Entcodierungs-Matrix
        :return: encoding matrix
        """
        return self.encode_matrix

    def encode(self, word):
        """
        Methode zum "encoden" eines Wortes"
        :param word: Wort zum "encoden"
        :return: "encoded" Wort
        """
        word_array = [int(x) for x in str(bin(word)[2:])]
        word_array_len = len(word_array)
        if word_array_len < self.p:
            for i in range(self.p - word_array_len):
                word_array.insert(0, 0)
        tmp_encode = np.where(np.matmul(self.gen_matrix, word_array) % 2 == 0, 0, 1)
        return ''.join(map(str, [int(x) for x in tmp_encode]))
        
        

    def decode(self, codeword):
        """
        Methode zum "decoden" eines Wortes
        :param codeword: Wort zum "decoden"
        :return: "decoded" Wort
        """
        codeword_array = self.__to_array(codeword)
        decoded_word = np.where(np.matmul(self.encode_matrix, codeword_array) % 2 == 0, 0, 1)
        return decoded_word

    def check(self, codeword):
        """
        Methode zum prüfen der Gültigkeit eines Codewortes.
        :param codeword: Codewort zum prüfen
        :return: "True" wenn das wort korrekt ist, "False" wen das codewort fehler hat.
        """
        codeword_array = self.__to_array(codeword)
        check = np.where(np.matmul(self.chk_matrix, codeword_array) % 2 == 0, 0, 1)
        error = sum(int(check) * (2 ** i) for i, check in enumerate(check[::-1]))
        print("Error in bit: ", error)
        return ''.join(map(str, [int(x) for x in check]))

### Ausführung
Die Klasse kann nun im Python Code verwendet werden. Mit dem Aufruf `HamingCode(k)` wird eine Instanz der Klasse erzeugt mit $k$ Paritätsbits. Mir den verwschiedenen Methoden der Klasse können nun ausgaben generiert werden. So ist 


In [51]:
import numpy as np

def main():
    k = 3
    hamming = HammingCode(k)
    print("Length: ", hamming.get_length())
    print("Payload: ", hamming.get_payload())
    print("Generator Matrix: ", hamming.get_generator_matrix())
    print("Check Matrix: ", hamming.get_check_matrix())
    print("Encoding Matrix: ", hamming.get_encoding_matrix())

    for w in range(hamming.get_payload()**2):
        encode_decode(hamming, w)

    # Hamminc Code with error:
    print("Hamming-Code with error")
    codeword_with_error = "0111011"
    print("Codeword with error: ", codeword_with_error)
    check = hamming.check(codeword_with_error)
    print("Check Result: ", check)

     # Hamminc Code with error:
    print("Hamming-Code with error")
    codeword_with_error_2 = "1110011"
    print("Codeword with error: ", codeword_with_error_2)
    print("Check Matrix:\n ", hamming.get_check_matrix())
    check = hamming.check(codeword_with_error_2)
    print("Check Result: ", check)
    


def encode_decode(hamming, word):
    print("Word: ", word)
    encoded_word = hamming.encode(word)
    print("Encoded Word: ", encoded_word)
    check = hamming.check(encoded_word)
    print("Check Result: ", check)
    decoded_word = hamming.decode(encoded_word)
    print("Decoded Word: ", decoded_word)


if __name__ == '__main__':
    main()


Length:  7
Payload:  4
Generator Matrix:  [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 1. 0. 1.]
 [1. 0. 1. 1.]
 [0. 1. 1. 1.]]
Check Matrix:  [[1. 1. 0. 1. 1. 0. 0.]
 [1. 0. 1. 1. 0. 1. 0.]
 [0. 1. 1. 1. 0. 0. 1.]]
Encoding Matrix:  [[0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
Word:  0
Encoded Word:  0000000
Error in bit:  0
Check Result:  000
Decoded Word:  [0 0 0 0]
Word:  1
Encoded Word:  0001111
Error in bit:  0
Check Result:  000
Decoded Word:  [1 1 1 1]
Word:  2
Encoded Word:  0010011
Error in bit:  0
Check Result:  000
Decoded Word:  [0 0 1 1]
Word:  3
Encoded Word:  0011100
Error in bit:  0
Check Result:  000
Decoded Word:  [1 1 0 0]
Word:  4
Encoded Word:  0100101
Error in bit:  0
Check Result:  000
Decoded Word:  [0 1 0 1]
Word:  5
Encoded Word:  0101010
Error in bit:  0
Check Result:  000
Decoded Word:  [1 0 1 0]
Word:  6
Encoded Word:  0110110
Error in bit:  0
Check Result:  000
Decoded Word:  [0 1 1 0

## Literatur
[Weitz. 2018. *Konkrete Mathematik (nicht nur) für Informatiker: mit vielen Grafiken und Algorithmen in Python*](zotero://select/items/_C9DWSI2S)

[Teschl. 2013. *Mathematik für Informatiker: Band 1: Diskrete Mathematik und Lineare Algebra*](zotero://select/items/_85KJXNKN)

[Socher. 2022. *Mathematik für Informatiker: diskrete Mathematik, lineare Algebra und Wahrscheinlichkeitsrechnung*](zotero://select/items/_QGF4J2P6)

[2020. * Wikipedia: Hamming-Code*](zotero://select/items/_8C9CJA2Z)