# LinAlg - Block 4



In [25]:
import numpy as np
import pprint
import numpy.linalg as la
from math import pi, cos, sqrt

a = np.array([4,1,2])
b = np.array([4,5,6])

print(la.norm(a))
la.norm(b)

print(np.dot(a, b))
print(np.cross(a, b))

alpha = cos(np.dot(a, b)/(la.norm(a)*la.norm(b)))*(180/pi)

print(alpha)

# Aufgabe 4 Moodle Block 4
u1 = np.array([3,1,1])
u2 = np.array([-1,2,1])
u3 = np.array([-1,-4,7])
x = np.array([6,-4,8])

l1 = np.vdot(x, u1)/np.vdot(u1,u1)
l2 = np.vdot(x, u2)/np.vdot(u2,u2)
l3 = np.vdot(x, u3)/np.vdot(u3,u3)
print(l1)
print(l2)
print(l3)

u1 = np.array([2,1,0])
a2 = np.array([1,0,-1])
print(np.vdot(u1, a2)) 

a1 = np.array([2,0,1])
a2 = np.array([1,-1,0])
a3 = np.array([0,2,-1])

u1 = a1/la.norm(a1)
pprint.pprint(u1)
u2 = (a2 - np.dot((1/sqrt(5)*a1), a2)*a1)/la.norm(a2 - np.dot((1/sqrt(5)*a1), a2)*a1)
pprint.pprint(u2)
#print(np.dot((1/sqrt(5)*a1), a2))




4.58257569495584
33
[ -4 -16  16]
39.061082366446406
2.0
-1.0
1.0
2
array([0.89442719, 0.        , 0.4472136 ])
array([-0.50685492, -0.64252025, -0.57468758])
